version: '2.2'

services:

  db:
    image: postgres:12.1
    volumes:
      - pgdata:/var/lib/postgresql/data
      - '.dockerdev/init.sql:/docker-entrypoint-initdb.d/init.sql'
      - bundle:/usr/local/bundle
    ports:
      - '5432:5432'
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

  webpack:
    build: .
    command: ./bin/webpack-dev-server --inline true
    volumes:
      - '.:/railsapp'
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
    ports:
      - '3035:3035'

  web:
    build: .
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - '.:/railsapp'
      - .dockerdev/.bashrc:/root/.bashrc:ro
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - db
      - webpack

volumes:
  bundle:
  pgdata:
  node_modules:
